// Generated by CoffeeScript 1.8.0
Epicport.Login = (function() {
  function Login(options) {
    Epicport.profile = options.data;
    $.cookie('profile', JSON.stringify(Epicport.profile), {
      expires: 356,
      path: '/'
    });
    $(".login_modal").dialog("close");
  }

  return Login;

})();

Epicport.login = function(options) {
  options || (options = {});
  if (!(typeof Module === 'undefined')) {
    Module['disable_sdl_envents'] = true;
  }
  return $(".login_modal").dialog({
    modal: true,
    width: 500,
    close: function() {
      if (!(typeof Module === 'undefined')) {
        Module['disable_sdl_envents'] = false;
      }
      return options.callback();
    }
  });
};
