// Generated by CoffeeScript 1.8.0
Epicport.Navbar = (function() {
  function Navbar() {
    this.loginLink = $('#navbar_login_link');
    this.logoutLink = $('#navbar_logout_link');
    this.name = $('#navbar_name');
    $('#navbar_login_link, #navbar_logout_link').click((function(_this) {
      return function() {
        Epicport.login({
          callback: function() {
            return _this.reset();
          }
        });
        return false;
      };
    })(this));
    this.reset();
  }

  Navbar.prototype.reset = function() {
    if (Epicport.profile) {
      this.loginLink.hide();
      this.logoutLink.show();
      this.name.html(Epicport.profile.first_name);
      return this.name.show();
    } else {
      this.loginLink.show();
      this.logoutLink.hide();
      return this.name.hide();
    }
  };

  return Navbar;

})();
