// Generated by CoffeeScript 1.8.0
Epicport.XCOM = (function() {
  function XCOM() {
    $("#xcom_data_link").click(function() {
      $("#input_xcom_data_link").val($("#xcom_data_link").attr("href"));
      return false;
    });
  }

  XCOM.prototype.start = function() {
    var startGame;
    Module['openxcom.data'] = "/storage/proxy?url=https://dl.dropboxusercontent.com/s/kp9i4z5qtpede1d/openxcom.data";
    startGame = (function(_this) {
      return function() {
        return $.ajax({
          url: "openxcom.js",
          dataType: "script",
          xhr: function() {
            var xhr;
            Module.setStatus("Downloading script (openxcom.js)");
            xhr = $.ajaxSettings.xhr();
            xhr.addEventListener("progress", function(evt) {
              if (evt.lengthComputable) {
                return Epicport.API.progress(evt.loaded, evt.total);
              }
            });
            return xhr;
          }
        });
      };
    })(this);
    return setTimeout(startGame, 500);
  };

  return XCOM;

})();
