// Generated by CoffeeScript 1.8.0
Epicport.Caesaria = (function() {
  function Caesaria() {}

  Caesaria.prototype.start = function() {
    var startGame;
    startGame = (function(_this) {
      return function() {
        return $.ajax({
          url: "/emscripten/caesaria/caesaria.js",
          dataType: "script",
          xhr: function() {
            var xhr;
            Module.setStatus("Downloading script (caesaria.js)");
            xhr = $.ajaxSettings.xhr();
            xhr.addEventListener("progress", function(evt) {
              if (evt.lengthComputable) {
                return Epicport.API.progress(evt.loaded, evt.total);
              }
            });
            return xhr;
          }
        });
      };
    })(this);
    return setTimeout(startGame, 500);
  };

  return Caesaria;

})();
