// Generated by CoffeeScript 1.8.0
Epicport.Ttd = (function() {
  function Ttd() {}

  Ttd.prototype.start = function(jsFile) {
    var startGame;
    $(".canvas_container").width($(window).width());
    $(".canvas_container").height($(window).height());
    $(window).scrollTop($(".canvas_container").offset().top);
    Epicport.API.Module["arguments"].push('-r');
    Epicport.API.Module["arguments"].push($(".canvas_container").width() + 'x' + $(".canvas_container").height());
    startGame = (function(_this) {
      return function() {
        return $.ajax({
          url: jsFile,
          dataType: "script",
          xhr: function() {
            var xhr;
            Module.setStatus("Downloading script (" + jsFile + ")");
            xhr = $.ajaxSettings.xhr();
            xhr.addEventListener("progress", function(evt) {
              if (evt.lengthComputable) {
                return Epicport.API.progress(evt.loaded, evt.total);
              }
            });
            return xhr;
          }
        });
      };
    })(this);
    return setTimeout(startGame, 500);
  };

  return Ttd;

})();
